# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LWOSSURLSplice' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LWOSSURLSplice
  pod 'Masonry'
  pod 'SDWebImage'
  target 'LWOSSURLSpliceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LWOSSURLSpliceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
